### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by Yaron10** [Yaron10/compare-plugin-Pavel-Nedev#8]
Hello @MetaChuh,

Thank you for closing the old issues in NPP repo.
I coudn't write earlier.

BR

**Comment by MetaChuh** [comment]
hi @Yaron10 

loooool ... now **THAT** gives the wording "communication issue" a completely new meaning !
it's so much better to talk **WITH** communication issues 😂

nice idea 👍

**Comment by Yaron10** [comment]
Hello @MetaChuh,

When One Door Closes, A Window Opens... :)

Thank you. :+1: 

BR

**Comment by MetaChuh** [comment]
hehe, don't worry, you can comment anytime at any of the closed issues for feedback, information, or just for the fun of it ;-)

we're just doing a cleanup of the old, abandoned or outdated issues to be able to read and breath again at the tracker.
some will, of course, be filed again as they still persist in one way or the other, some will not, as the author's don't care anymore.

currently we have to do that, due to the size of the notepad++ project.
so many leftovers from the past, many untracked duplicates and incomprehensible requests, all of which accumulated, as it was not possible to cope with all of them at the time.

we will try to do it better in the future.

greetings and many thanks again for your support

**Comment by Yaron10** [comment]
I didn't want to bother thousands of followers with my comments.

Thanks again for your important work. It's highly appreciated.

Best regards.
